# Generated by Django 3.2.9 on 2022-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(max_length=50, verbose_name='Hobbies del familiar')),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=15, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, max_length=30, verbose_name='Nombre Completo')),
                ('relative', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hermano', 'Hermano'), ('esposa', 'Esposa'), ('hijo', 'Hijo'), ('hija', 'Hija')], max_length=50, verbose_name='Parentesco')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='familia')),
                ('hobbies', models.ManyToManyField(to='personas.Hobbies')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
                'ordering': ['-first_name', 'last_name'],
            },
        ),
    ]
