# Generated by Django 3.2.9 on 2022-04-03 20:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20220403_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiar',
            options={'ordering': ['-id', 'last_name'], 'verbose_name': 'Familiar', 'verbose_name_plural': 'Familiares'},
        ),
        migrations.AddField(
            model_name='familiar',
            name='bio',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='relative',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hermano', 'Hermano'), ('esposa', 'Esposa'), ('hijo', 'Hijo'), ('hija', 'Hija'), ('mascota', 'Mascota')], max_length=50, verbose_name='Parentesco'),
        ),
    ]
